export const endPoints = {
  AUTH: {
    LOGIN: '/auth/login',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    LOGOUT: '/auth/logout',
    CHANGE_PASSWORD: '/auth/change-password',
    ME: '/auth/me',
  },
  ORGANIZATION: {
    CREATE_MEMBER: '/organization-members',
    GET_MEMBERS: '/organization-members',
    ASSIGN_SERVICES: '/organization-members',
    ASSIGN_CUSTOM_SERVICES: '/organization-members',
  },
  CUSTOM_SERVICE: {
    GET_ACTIVE: '/custom-services/active',
  },
  NOTICE: {
    GET_TODAY: '/notices/today',
  },
  NOTIFICATION: {
    BASE: '/notifications',
    UNREAD_COUNT: '/notifications/unread-count',
    MARK_READ: (id: string) => `/notifications/read/${id}`,
    MARK_ALL_READ: '/notifications/read-all',
    PREFERENCES: '/notifications/preferences',
  },
  ENGAGEMENTS: {
    GET_ALL: '/engagements',
    GET_BY_ID: (engagementId: string) => `/engagements/${engagementId}`,
    UPDATE_STATUS: (engagementId: string) => `/engagements/${engagementId}/status`,
    CHECKLISTS: (id: string) => `/engagements/${id}/checklists`,
    CHECKLIST_BY_ID: (engId: string, checklistId: string) => `/engagements/${engId}/checklists/${checklistId}`,
    CHECKLIST_STATUS: (engId: string, checklistId: string) => `/engagements/${engId}/checklists/${checklistId}/status`,
    COMPLIANCES: (id: string) => `/engagements/${id}/compliances`,
    TEAM: (engagementId: string) => `/engagements/${engagementId}/team`,
    CHAT_ROOM: (engagementId: string) => `/chat/engagements/${engagementId}/room`,
    MILESTONES: (engagementId: string) => `/engagements/${engagementId}/milestones`,
    LIBRARY_FOLDER: (engagementId: string) => `/engagements/${engagementId}/library`,
    LIBRARY_FOLDER_BY_TYPE: (engagementId: string, type: string) => `/engagements/${engagementId}/library?type=${type}`,
    EVIDENCE_FOLDER: (engagementId: string) => `/engagements/${engagementId}/library/evidences`,
    WORKBOOK_FOLDER: (engagementId: string) => `/engagements/${engagementId}/library/workbooks`,
  },
  ENGAGEMENT_UPDATES: '/engagement-updates',
  DOCUMENT_REQUESTS: '/document-requests',
  REQUESTED_DOCUMENTS: (requestId: string) => `/document-requests/${requestId}/documents`,
  REQUESTED_DOCUMENT_BY_ID: (requestId: string, docId: string) => `/document-requests/${requestId}/documents/${docId}`,
  REQUESTED_DOCUMENT_UPLOAD: (requestId: string, docId: string) => `/document-requests/${requestId}/documents/${docId}/upload`,
  COMPLIANCE_CALENDAR: {
    BASE: '/compliance-calendar',
    GET_BY_ID: (id: string) => `/compliance-calendar/${id}`
  },
  CHAT: {
    ROOMS: '/chat/rooms',
    ROOM_BY_ID: (roomId: string) => `/chat/rooms/${roomId}`,
    MEMBERS: (roomId: string) => `/chat/rooms/${roomId}/members`,
    MEMBER_DELETE: (roomId: string, userId: string) => `/chat/rooms/${roomId}/members/${userId}`,
    MESSAGES: (roomId: string) => `/chat/rooms/${roomId}/messages`,
    CLEAR_MESSAGES: (roomId: string) => `/chat/rooms/${roomId}/messages`,
    NOTIFY_MEMBERS: (roomId: string) => `/chat/rooms/${roomId}/notify-members`,
    MARK_READ: (roomId: string) => `/chat/rooms/${roomId}/read`,
    UNREAD_COUNT: (roomId: string) => `/chat/rooms/${roomId}/unread-count`,
    UNREAD_SUMMARY: '/chat/unread-summary',
    UPLOAD: '/chat/upload',
  },
  LIBRARY: {
    FOLDERS_ROOTS: '/library/folders/roots',
    FOLDER_CONTENT: (folderId: string) => `/library/folders/${folderId}/content`,
    FOLDER_CREATE: '/library/folders',
    FILE_UPLOAD: '/library/files/upload',
    FILE_DELETE: (fileId: string) => `/library/files/${fileId}`,
    FOLDER_DELETE: (folderId: string) => `/library/folders/${folderId}`,
  },
  COMPANY: {
    BASE: '/companies',
    GET_BY_ID: (id: string) => `/companies/${id}`,
  },
  AUDIT: {
    CREATE_CYCLE: '/audit-cycles',
    GET_CYCLE: (id: string) => `/audit-cycles/${id}`,
    GET_CYCLES: '/audit-cycles',
    UPLOAD_TRIAL_BALANCE: (auditCycleId: string) => `/uploadapi/v1/services/audit/${auditCycleId}/trial-balance`,
    GET_TRIAL_BALANCES: (auditCycleId: string) => `/audit-cycles/${auditCycleId}/trial-balances`,
    GET_TRIAL_BALANCE_WITH_ACCOUNTS: (auditCycleId: string, trialBalanceId: string) => `/audit-cycles/${auditCycleId}/trial-balances/${trialBalanceId}/with-accounts`,
    GET_CLASSIFICATION_MAP: '/classifications/map',
    UPDATE_TRIAL_BALANCE_ACCOUNTS: (auditCycleId: string, trialBalanceId: string) => `/audit-cycles/${auditCycleId}/trial-balances/${trialBalanceId}/accounts`,
    CREATE_AUDIT_ENTRY: (auditCycleId: string, trialBalanceId: string) => `/audit-cycles/${auditCycleId}/trial-balances/${trialBalanceId}/audit-entries`,
    GET_AUDIT_ENTRIES: (auditCycleId: string, trialBalanceId: string) => `/audit-cycles/${auditCycleId}/trial-balances/${trialBalanceId}/audit-entries`,
    GET_AUDIT_ENTRY: (auditCycleId: string, trialBalanceId: string, entryId: string) => `/audit-cycles/${auditCycleId}/trial-balances/${trialBalanceId}/audit-entries/${entryId}`,
    UPDATE_AUDIT_ENTRY: (auditCycleId: string, trialBalanceId: string, entryId: string) => `/audit-cycles/${auditCycleId}/trial-balances/${trialBalanceId}/audit-entries/${entryId}`,
    DELETE_AUDIT_ENTRY: (auditCycleId: string, trialBalanceId: string, entryId: string) => `/audit-cycles/${auditCycleId}/trial-balances/${trialBalanceId}/audit-entries/${entryId}`,
    GET_INCOME_STATEMENT: (engagementId: string) => `/services/audit/engagements/${engagementId}/financial-reports/income-statement`,
    GET_BALANCE_SHEET: (engagementId: string) => `/services/audit/engagements/${engagementId}/financial-reports/balance-sheet`,
    // Evidence endpoints
    GET_EVIDENCES: '/evidences',
    GET_EVIDENCE: (evidenceId: string) => `/evidences/${evidenceId}`,
    CREATE_EVIDENCE: '/evidences',
    UPDATE_EVIDENCE: (evidenceId: string) => `/evidences/${evidenceId}`,
    DELETE_EVIDENCE: (evidenceId: string) => `/evidences/${evidenceId}`,
    // Classification endpoints
    GET_CLASSIFICATIONS: '/classifications',
    GET_CLASSIFICATION: (classificationId: string) => `/classifications/${classificationId}`,
    CREATE_CLASSIFICATION: '/classifications',
    FIND_CLASSIFICATION_BY_GROUPS: '/classifications/find-by-groups',
    // Workbook endpoints
    GET_WORKBOOKS: '/workbooks',
    GET_WORKBOOK: (workbookId: string) => `/workbooks/${workbookId}`,
    CREATE_WORKBOOK: '/workbooks',
    UPDATE_WORKBOOK: (workbookId: string) => `/workbooks/${workbookId}`,
    DELETE_WORKBOOK: (workbookId: string) => `/workbooks/${workbookId}`,
    GET_WORKBOOK_SHEETS: (workbookId: string) => `/workbooks/${workbookId}/sheets`,
    GET_WORKBOOK_SHEET_DATA: (workbookId: string, sheetName?: string) =>
      sheetName
        ? `/workbooks/${workbookId}/sheets/data?sheetName=${encodeURIComponent(sheetName)}`
        : `/workbooks/${workbookId}/sheets/data`,
    // RangeEvidence endpoints (for mappings and references)
    GET_RANGE_EVIDENCES: (workbookId: string) => `/workbooks/${workbookId}/range-evidences`,
    GET_RANGE_EVIDENCE: (workbookId: string, rangeEvidenceId: string) => `/workbooks/${workbookId}/range-evidences/${rangeEvidenceId}`,
    CREATE_RANGE_EVIDENCE: (workbookId: string) => `/workbooks/${workbookId}/range-evidences`,
    UPDATE_RANGE_EVIDENCE: (workbookId: string, rangeEvidenceId: string) => `/workbooks/${workbookId}/range-evidences/${rangeEvidenceId}`,
    DELETE_RANGE_EVIDENCE: (workbookId: string, rangeEvidenceId: string) => `/workbooks/${workbookId}/range-evidences/${rangeEvidenceId}`,
    ATTACH_EVIDENCE_TO_RANGE_EVIDENCE: (workbookId: string, rangeEvidenceId: string) => `/workbooks/${workbookId}/range-evidences/${rangeEvidenceId}/attach-evidence`,
  },
  INCORPORATION: {
    GET_BY_COMPANY: (companyId: string) => `/incorporation/company/${companyId}`,
  },
  TODO: {
    BASE: '/todos',
    BY_ENGAGEMENT: (engagementId: string) => `/engagements/${engagementId}/todos`,
    BY_ID: (todoId: string) => `/todos/${todoId}`,
    UPDATE_STATUS: (todoId: string) => `/todos/${todoId}/status`,
    FROM_CHAT: (engagementId: string) => `/engagements/${engagementId}/todos/from-chat`,
    FROM_DOCUMENT_REQUEST: (engagementId: string) => `/engagements/${engagementId}/todos/from-document-request`,
    FROM_REQUESTED_DOCUMENT: (engagementId: string) => `/engagements/${engagementId}/todos/from-requested-document`,
  },
  NOTIFICATIONS: {
    BASE: '/notifications',
    UNREAD_COUNT: '/notifications/unread-count',
    READ: (id: string) => `/notifications/read/${id}`,
    READ_ALL: '/notifications/read-all',
  },
  PROCEDURE_PROMPT: {
    BASE: '/procedure-prompts',
    GET_ALL: '/procedure-prompts',
    GET_BY_ID: (id: string) => `/procedure-prompts/${id}`,
    CREATE: '/procedure-prompts',
    UPDATE: (id: string) => `/procedure-prompts/${id}`,
    DELETE: (id: string) => `/procedure-prompts/${id}`,
  }
};
