export const endPoints = {
  AUTH: {
    LOGIN: '/auth/login',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    LOGOUT: '/auth/logout',
    CHANGE_PASSWORD: '/auth/change-password',
    ME: '/auth/me',
  },
  ORGANIZATION: {
    CREATE_MEMBER: '/organization-members',
    GET_MEMBERS: '/organization-members',
    ASSIGN_SERVICES: '/organization-members',
    ASSIGN_CUSTOM_SERVICES: '/organization-members',
  },
  CUSTOM_SERVICE: {
    GET_ACTIVE: '/custom-services/active',
  },
  NOTICE: {
    GET_TODAY: '/notices/today',
  },
  ENGAGEMENTS: {
    GET_ALL: '/engagements',
    GET_BY_ID: (engagementId: string) => `/engagements/${engagementId}`,
    CHECKLISTS: (id: string) => `/engagements/${id}/checklists`,
    CHECKLIST_BY_ID: (engId: string, checklistId: string) => `/engagements/${engId}/checklists/${checklistId}`,
    CHECKLIST_STATUS: (engId: string, checklistId: string) => `/engagements/${engId}/checklists/${checklistId}/status`,
    COMPLIANCES: (id: string) => `/engagements/${id}/compliances`,
    TEAM: (engagementId: string) => `/engagements/${engagementId}/team`,
    CHAT_ROOM: (engagementId: string) => `/chat/engagements/${engagementId}/room`,
    MILESTONES: (engagementId: string) => `/engagements/${engagementId}/milestones`,
    LIBRARY_FOLDER: (engagementId: string) => `/engagements/${engagementId}/library`,
    LIBRARY_FOLDER_BY_TYPE: (engagementId: string, type: string) => `/engagements/${engagementId}/library?type=${type}`,
  },
  ENGAGEMENT_UPDATES: '/engagement-updates',
  DOCUMENT_REQUESTS: '/document-requests',
  REQUESTED_DOCUMENTS: (requestId: string) => `/document-requests/${requestId}/documents`,
  REQUESTED_DOCUMENT_BY_ID: (requestId: string, docId: string) => `/document-requests/${requestId}/documents/${docId}`,
  REQUESTED_DOCUMENT_UPLOAD: (requestId: string, docId: string) => `/document-requests/${requestId}/documents/${docId}/upload`,
  CHAT: {
    ROOMS: '/chat/rooms',
    ROOM_BY_ID: (roomId: string) => `/chat/rooms/${roomId}`,
    MEMBERS: (roomId: string) => `/chat/rooms/${roomId}/members`,
    MEMBER_DELETE: (roomId: string, userId: string) => `/chat/rooms/${roomId}/members/${userId}`,
    MESSAGES: (roomId: string) => `/chat/rooms/${roomId}/messages`,
    MARK_READ: (roomId: string) => `/chat/rooms/${roomId}/read`,
    UNREAD_SUMMARY: '/chat/unread-summary',
    UPLOAD: '/chat/upload',
  },
  LIBRARY: {
    FOLDERS_ROOTS: '/library/folders/roots',
    FOLDER_CONTENT: (folderId: string) => `/library/folders/${folderId}/content`,
    FOLDER_CREATE: '/library/folders',
    FILE_UPLOAD: '/library/files/upload',
    FILE_DELETE: (fileId: string) => `/library/files/${fileId}`,
    FOLDER_DELETE: (folderId: string) => `/library/folders/${folderId}`,
  },
  COMPANY: {
    BASE: '/companies',
    GET_BY_ID: (id: string) => `/companies/${id}`,
  },
};
