// src/static/procedures.ts

type ProcItem = {
  id: string
  question: string
  isRequired?: boolean
  // you can add any other fields you want carried through (e.g., help, area, etc.)
}

type ProcMap = Record<string, ProcItem[]>

const procedures: ProcMap = {
  "Bank and Cash": [
    { id: "bc_1", question: "Obtain bank confirmations for all active accounts.", isRequired: true },
    { id: "bc_2", question: "Perform bank reconciliation testing for month-end and year-end balances." },
    { id: "bc_3", question: "Review unusual or large cash transfers near period end." },
    { id: "bc_ifrs_1", question: "Risk Assessment & Response Design - Key IFRS risks: unrecorded accounts/loans, offsetting contrary to IAS 32, incorrect cash equivalents policy (IAS 7), FX translation (IAS 21), undisclosed restrictions, covenant breaches, window dressing.", isRequired: true },
    { id: "bc_ifrs_2", question: "Opening Balances & Lead Schedule - Agree opening balances to prior audited FS; obtain/prepare lead schedule and agree to GL; investigate unusual movements." },
    { id: "bc_ifrs_3", question: "Bank Reconciliations & Cash Control - Review bank recs for all accounts; trace deposits in transit and outstanding cheques to subsequent statements; review cash control account and differences." },
    { id: "bc_ifrs_4", question: "External Confirmations (ISA 505) - Obtain direct bank confirmations: balances, facilities, security/charges, guarantees, legal right of set-off; agree to statements and GL." },
    { id: "bc_ifrs_5", question: "Cash Counts (where applicable) - Perform/observe cash counts; reconcile to cash book; investigate discrepancies." },
    { id: "bc_ifrs_6", question: "Statement Review & Unusual Items - Review all bank statements for the period and shortly after year end; identify and corroborate large/unusual items; search for unrecorded liabilities/assets." },
    { id: "bc_ifrs_7", question: "Cut-off, Interest & Fees - Test period-end cut-off; reperform interest and fees; verify that reconciling items clear in the subsequent period." },
    { id: "bc_ifrs_8", question: "Foreign Currency (IAS 21) - Recalculate FX translation of foreign currency accounts at the reporting date; verify recognition of FX gains/losses and disclosures." },
    { id: "bc_ifrs_9", question: "Classification, Offsetting & Cash Equivalents - Evaluate classification of cash/cash equivalents per IAS 7; assess offsetting per IAS 32; identify restricted cash and required disclosures (IAS 1/IFRS 7)." },
    { id: "bc_ifrs_10", question: "Loans & Facilities (IFRS 7) - Agree loan balances/terms to confirmations and agreements; test accrued interest; assess covenant compliance and disclosure of liquidity risk maturity analyses if material." },
    { id: "bc_ifrs_11", question: "Window Dressing & End-of-period Engineering - Evaluate for temporary repayments/round-tripping; corroborate with subsequent period activity and facility utilization." },
    { id: "bc_gapsme_1", question: "Risk Assessment & Response Design - Consider risks: timing/cut-off, unrecorded bank accounts/loans, reconciling items not cleared, fictitious cash, offsetting, FX translation (GAPSME Sec. 18), window dressing.", isRequired: true },
    { id: "bc_gapsme_2", question: "Opening Balances & Lead Schedule - Agree opening bank/cash balances to prior FS; obtain/prepare lead schedule; reconcile to GL; investigate major variances vs expectations." },
    { id: "bc_gapsme_3", question: "Bank Reconciliations & Cash Control - Prepare/review bank recs for all accounts; trace outstanding items to the next-period statements; prepare/review cash control account and investigate reconciling differences." },
    { id: "bc_gapsme_4", question: "External Confirmation (ISA 505) - Obtain bank audit letters for all banking relationships; agree confirmed balances, facilities, securities, guarantees, covenants and legal right of set-off where applicable." },
    { id: "bc_gapsme_5", question: "Cash Count (if cash-based business) - Attend/perform cash count at/near year end; reconcile to cash book; investigate over/shorts." },
    { id: "bc_gapsme_6", question: "Unusual Items Review - Review recs for large/unusual reconciling items; inspect supporting documents; assess aging of unpresented cheques/LOD items." },
    { id: "bc_gapsme_7", question: "Bank Statement Scan - Scan all bank statements for the period and shortly after year end; investigate large/unusual receipts/payments; identify unrecorded accounts or liabilities." },
    { id: "bc_gapsme_8", question: "Cut-off & Valuation - Verify period-end cut-off for receipts/payments (e.g., deposits in transit, outstanding cheques); reperform interest/fees; ensure subsequent clearance of reconciling items." },
    { id: "bc_gapsme_9", question: "Foreign Currency (GAPSME Section 18) - Test translation of FCY bank balances at reporting date; review revaluation journals; verify recognition of FX differences per policy." },
    { id: "bc_gapsme_10", question: "Classification & Offsetting - Check classification of cash/cash equivalents vs restricted cash; verify no offsetting of overdrafts vs positive balances unless legal right of set-off exists and policy permits." },
    { id: "bc_gapsme_11", question: "Loans & Facilities - From bank letters and agreements, confirm loan balances, terms, interest, security/charges, covenants; test accrued interest and compliance." },
    { id: "bc_gapsme_12", question: "Window Dressing Indicators - Assess for atypical year-end transfers, temporary repayments, or circular cash movements; corroborate with post-year activity." },
    { id: "bc_gapsme_13", question: "Disclosures - Review notes for banking arrangements, restrictions, guarantees, security, related parties, cash equivalents policy and FX disclosures per GAPSME." },
    { id: "bc_gapsme_14", question: "Written Representations - Obtain management reps covering completeness of bank accounts/loans, accuracy of reconciliations, existence of restrictions/guarantees, FX treatment." },
    { id: "bc_gapsme_15", question: "Conclusion — Bank & Cash (GAPSME) - Conclude whether bank and cash are free from material misstatement; summarize exceptions and proposed adjustments." }
  ],

  "Equity": [
    { id: "eq_1", question: "Agree share capital and reserves to the general ledger and supporting registers.", isRequired: true },
    { id: "eq_2", question: "Inspect minutes for approvals of dividends and capital changes." },
    { id: "eq_3", question: "Recompute EPS where applicable and verify disclosures." },
    { id: "proc_ifrs_risk_response", question: "Risk Assessment & Response Design - Document identified equity risks (e.g., complex instruments, equity fraud) and associated audit responses.", isRequired: true },
    { id: "proc_ifrs_opening_tieback", question: "Opening Balance Tie-back - Agree opening equity balances to prior audited FS/SOCIE; investigate any differences." },
    { id: "proc_ifrs_lead_schedule", question: "Lead Schedule Reconciliation - Prepare and reconcile lead schedule for equity components against GL and SOCIE." },
    { id: "proc_ifrs_analytics", question: "Analytical Review -- Equity Movements - Perform comparative and ratio-based analytics to detect and investigate unusual equity movements." },
    { id: "proc_ifrs_trace_issues", question: "Trace Share Issues to Support - Inspect resolutions, subscription agreements, bank receipts, share certificates, MBR filings." },
    { id: "proc_ifrs_buybacks", question: "Buy-backs / Cancellations -- Compliance - Verify board approval, compliance with Companies Act, and registry filings." },
    { id: "proc_ifrs_capital_reductions", question: "Capital Reductions & Distributable Reserve Creation - Confirm legal procedures and filings under updated Companies Act (Act XVIII of 2024)." },
    { id: "proc_ifrs_reserves", question: "Reserve Movements Recalculation - Recompute reserve movements (opening + movement -- distribution = closing) and verify support." },
    { id: "proc_ifrs_dividends", question: "Dividends --- Legality & Recognition - Ensure dividends are declared in compliance with law and recorded from distributable profits." },
    { id: "proc_ifrs_classification", question: "Classification --- Equity vs Liability (IAS 32) - Assess form vs substance, especially for hybrid instruments and convertibles." },
    { id: "proc_ifrs_disclosures", question: "Disclosure Review --- IAS 1, IAS 32, IFRS 7 - Check that disclosures include share classes, reconciliations, rights, and instrument risk." },
    { id: "proc_ifrs_subsequent_events", question: "Subsequent Events --- Equity (ISA 560) - Review post-year-end minutes/filings for equity changes, assess need for adjustment or disclosure." },
    { id: "proc_ifrs_written_reps", question: "Written Representations --- Equity (ISA 580) - Obtain written rep from management covering completeness, classification, and legality." },
    { id: "proc_ifrs_conclusion", question: "Conclusion --- Equity (IFRS) - State if equity is free from material misstatement; reference any exceptions." },
    { id: "proc_gapsme_risk_response", question: "Risk Assessment & Response Design - Document identified equity-related risks under GAPSME (e.g., fair value elections, hybrid instruments) and responses.", isRequired: true },
    { id: "proc_gapsme_opening_tieback", question: "Opening Balance Tie-back - Agree opening balances to prior audited FS/SOCIE; investigate differences." },
    { id: "proc_gapsme_lead_schedule", question: "Lead Schedule Reconciliation - Reconcile lead schedule for equity components to GL and SOCIE." },
    { id: "proc_gapsme_analytics", question: "Analytical Review -- Equity Movements - Perform analytics and investigate fluctuations." },
    { id: "proc_gapsme_trace_issues", question: "Trace Share Issues to Support - Inspect supporting documents and MBR filings for share issues." },
    { id: "proc_gapsme_buybacks", question: "Buy-backs / Cancellations -- Compliance - Verify legal compliance, approvals, and registry filings." },
    { id: "proc_gapsme_capital_reductions", question: "Capital Reductions & Reserve Conversion - Check reductions and distributable reserve creation per Companies Act 2024." },
    { id: "proc_gapsme_reserves", question: "Reserve Movements Recalculation - Recompute reserve changes and verify notes/minutes/legal support." },
    { id: "proc_gapsme_dividends", question: "Dividends -- Legality & Recognition - Check dividends declared are lawful, from distributable profit, and recorded properly." },
    { id: "proc_gapsme_classification", question: "Classification -- GAPSME §9 & Hybrid Instruments - Evaluate classification and split for instruments with liability and equity elements." },
    { id: "proc_gapsme_fvtpl", question: "FVTPL Election -- Testing & Disclosure - Where fair value through profit or loss election used, test valuation and disclosures." },
    { id: "proc_gapsme_disclosures", question: "Equity Disclosures -- GAPSME §9.46 - Verify required disclosures (share movements, equity composition, reserves) are complete." },
    { id: "proc_gapsme_subsequent_events", question: "Subsequent Events --- Equity (ISA 560) - Review post-year changes such as share issues, cancellations, dividend declarations. Assess adjustment/disclosure needs." },
    { id: "proc_gapsme_written_reps", question: "Written Representations --- Equity (ISA 580) - Obtain representation from management on completeness of equity transactions, correct classification, and legality." },
    { id: "proc_gapsme_conclusion", question: "Conclusion --- Equity (GAPSME) - Conclude on whether equity is free from material misstatement; reference any exceptions." }
  ],

  "Borrowings and Loans": [
    { id: "bl_1", question: "Obtain loan confirmations and agree key terms to agreements.", isRequired: true },
    { id: "bl_2", question: "Test interest expense accruals and recompute effective interest." },
    { id: "bl_3", question: "Assess covenant compliance and evaluate classification impacts." },
    { id: "bl_ifrs_1", question: "Risk Assessment & Response Design - IFRS-specific risks: incorrect amortised cost/effective interest (IFRS 9), modification/extinguishment errors, inappropriate offsetting (IAS 32), breach-driven reclassification (IAS 1), missing IFRS 7 disclosures, FX retranslation (IAS 21).", isRequired: true },
    { id: "bl_ifrs_2", question: "Opening Balances & Lead Schedule - Agree opening borrowings to prior audited FS; prepare/review lead schedule; reconcile to GL; investigate unusual movements." },
    { id: "bl_ifrs_3", question: "External Confirmations (ISA 505) - Obtain direct confirmations for all lenders/facilities; agree principal, accrued interest, undrawn lines, security, guarantees and covenant clauses." },
    { id: "bl_ifrs_4", question: "Agreements, Covenants & Classification - Review contracts/waivers; test covenant compliance at reporting date; determine current vs non-current classification (IAS 1) and impact of waivers/refinancing." },
    { id: "bl_ifrs_5", question: "Completeness & Unrecorded Loans - Roll-forward opening→closing with movements; scan bank statements/GL for borrowing-type transactions; review board minutes for new debt approvals." },
    { id: "bl_ifrs_6", question: "Valuation --- Amortised Cost & EIR - Reperform effective interest calculations (IFRS 9), including fees/transaction costs; verify interest accruals and check subsequent settlements." },
    { id: "bl_ifrs_7", question: "Modifications & Extinguishments - For restructurings, perform IFRS 9 10% test; assess derecognition vs modification accounting; verify gain/loss recognition and revised EIR." },
    { id: "bl_ifrs_8", question: "FX & Variable-rate Loans - Recalculate IAS 21 retranslation at reporting date; verify interest calculations for variable rates and hedging impacts if applicable (disclose under IFRS 7)." },
    { id: "bl_ifrs_9", question: "Large/Unusual Items & New Loans - Review unusual entries; test new loans to agreements; confirm bona fide business purpose and proper authorization." },
    { id: "bl_ifrs_10", question: "Offsetting & Cash Pooling - Assess any offsetting or notional cash pooling against IAS 32 criteria and legal right of set-off; ensure appropriate presentation." },
    { id: "bl_ifrs_11", question: "Disclosures --- IFRS 7/IAS 1 - Audit disclosures: terms, maturities, interest rates, security/guarantees, covenant breaches/waivers, liquidity risk (maturity analysis), fair value hierarchy if disclosed, related parties." },
    { id: "bl_ifrs_12", question: "Written Representations - Obtain management reps on completeness of borrowing arrangements, covenant compliance, existence of waivers, security and proper classification/measurement." },
    { id: "bl_ifrs_13", question: "Conclusion --- Borrowings & Loans (IFRS) - Conclude whether borrowings are free from material misstatement; document exceptions and proposed adjustments." },
    { id: "bl_gapsme_1", question: "Risk Assessment & Response Design - Key risks: unrecorded loans, misstatement of interest/fees, covenant breaches, incorrect current/non-current split, undisclosed security/guarantees, FX/variable-rate issues.", isRequired: true },
    { id: "bl_gapsme_2", question: "Opening Balances & Lead Schedule - Agree opening borrowings to prior FS; obtain/prepare lead schedule; reconcile to GL; investigate major movements vs expectations." },
    { id: "bl_gapsme_3", question: "External Confirmations (ISA 505) - Obtain third-party confirmations/bank audit letters for all material loans/facilities; agree principal, accrued interest, undrawn facilities, security/guarantees and covenants." },
    { id: "bl_gapsme_4", question: "Agreements & Covenants - Review loan agreements/sanction letters; verify terms, repayment schedules, interest basis and compliance with covenants; assess impact on classification and disclosures." },
    { id: "bl_gapsme_5", question: "Completeness & Roll-forward - Compare period-end loan listing to opening balances plus movements; scan GL/bank statements for unrecorded loans; investigate new/closed facilities." },
    { id: "bl_gapsme_6", question: "Large/Unusual Items - Review unusual transactions per loan account; trace to supporting documentation and approvals." },
    { id: "bl_gapsme_7", question: "Valuation --- Interest & Fees - Reperform interest, fees and amortisation (if applicable); verify accrued interest at year-end and subsequent settlements." },
    { id: "bl_gapsme_8", question: "Classification (Current vs Non-current) - Confirm current/non-current split from agreements and covenant status; assess any breaches/waivers and refinancing after year-end for presentation." },
    { id: "bl_gapsme_9", question: "FX & Variable-rate Considerations - For foreign-currency/variable-rate loans, test period-end remeasurement and interest calculations; verify posting of FX differences per policy." },
    { id: "bl_gapsme_10", question: "Related Parties - Identify related-party loans; agree to agreements; review arm's-length terms and ensure disclosures." },
    { id: "bl_gapsme_11", question: "Disclosures - Compile information to audit disclosures: interest rates, maturities, security/guarantees, covenant status, undrawn facilities, related parties and restrictions." },
    { id: "bl_gapsme_12", question: "Written Representations - Obtain management reps on completeness of borrowings, covenant compliance/waivers, security/guarantees and classification." },
    { id: "bl_gapsme_13", question: "Conclusion --- Borrowings & Loans (GAPSME) - Conclude on existence, completeness, valuation and classification; summarize exceptions and proposed adjustments." }
  ],

  "Intangible Assets": [
    { id: "int_ifrs_risk_response", question: "Risk Assessment & Response Design - Document identified risks (e.g., improper capitalization, impairment risks) and audit responses.", isRequired: true },
    { id: "int_ifrs_opening_tieback", question: "Opening Balances Tie-back - Agree opening intangible balances to prior FS; investigate significant differences." },
    { id: "int_ifrs_lead_schedule", question: "Lead Schedule Reconciliation - Ensure the intangible assets schedule reconciles to the GL and disclosures." },
    { id: "int_ifrs_analytics", question: "Analytical Review -- Intangible Movements - Perform analytical reviews on additions, disposals, and amortization for anomalies." },
    { id: "int_ifrs_additions", question: "Review Additions and Recognition (IAS 38) - Vouch additions to contracts, verify that recognition criteria are met (identifiable asset, future benefit, reliable cost)." },
    { id: "int_ifrs_disposals", question: "Review Disposals & Derecognition - Ensure disposals are deregistered properly with gain/loss recorded in P&L." },
    { id: "int_ifrs_amortisation", question: "Amortisation Calculation Review - Recalculate amortisation; verify useful lives and methods per policy." },
    { id: "int_ifrs_impairment", question: "Impairment Testing (IAS 36) - Assess whether any indicators of impairment exist; test calculations and related disclosures." },
    { id: "int_ifrs_title_docs", question: "Legal Title Verification - Inspect contracts or legal agreements to ensure ownership rights." },
    { id: "int_ifrs_amortisation_cutoff", question: "Cut-off Testing --- Amortisation & Additions - Ensure amortisation and additions align with period to calculate expense correctly." },
    { id: "int_ifrs_disclosures", question: "Disclosure Review -- IAS 38 - Verify full disclosures on useful lives, amortisation methods, impairment, additions, and disposals." },
    { id: "int_ifrs_subsequent_events", question: "Subsequent Events --- Intangibles - Review post-year-end events affecting intangibles; consider adjustments or disclosures." },
    { id: "int_ifrs_written_reps", question: "Written Representations --- Intangibles - Obtain representations on completeness, valuation policies, and rights of intangible assets." },
    { id: "int_ifrs_conclusion", question: "Conclusion --- Intangible Assets (IFRS) - Provide overall conclusion on intangible assets; reference exceptions, if any." },
    { id: "ga_gapsme_1", question: "Risk Assessment & Response Design - Document risks around improper capitalization, amortisation, impairment, ownership, and plan audit responses.", isRequired: true },
    { id: "ga_gapsme_2", question: "Opening Balances Tie-back - Agree opening balances of intangible assets to prior FS; investigate material differences." },
    { id: "ga_gapsme_3", question: "Lead Schedule Reconciliation - Reconcile intangible assets schedule to GL and financial statement notes." },
    { id: "ga_gapsme_4", question: "Analytical Review of Movements - Perform analytics on additions, disposals, amortisation to uncover anomalies." },
    { id: "ga_gapsme_5", question: "Review Additions --- Capitalisation Criteria (Section 11) - Vouch additions; verify recognition criteria and that only cost model is applied (no revaluation permitted)." },
    { id: "ga_gapsme_6", question: "Review Disposals & Derecognitions - Ensure disposals are properly removed from schedule, and any gain/loss is recorded." },
    { id: "ga_gapsme_7", question: "Amortisation Calculations Review - Recalculate amortisation; ensure useful lives and methods align with accounting policy; goodwill amortised max 20 years, else write-off over 10 years." },
    { id: "ga_gapsme_8", question: "Impairment Review (Section 12) - Assess if indicators exist; test impairment loss calculation and reversal; verify disclosures (reason, amount, asset nature, method)." },
    { id: "ga_gapsme_9", question: "Verification of Legal Title - Check supporting documentation to confirm ownership or control of intangible assets." },
    { id: "ga_gapsme_10", question: "Cut-off Testing -- Additions & Amortisation - Test transactions around period-end to confirm timing of recognition and amortisation." },
    { id: "ga_gapsme_11", question: "Disclosure Review -- Section 11 & 12 - Verify disclosures: useful lives/amortisation rates, methods, opening/closing amounts, reconciliation of movements (additions, disposals, amortisation, impairment), and impairment details (loss/reversal, causes, recoverable method, classes affected)." },
    { id: "ga_gapsme_12", question: "Subsequent Events --- Intangibles - Review post-year-end events affecting intangibles (e.g., impairment, disposals) for adjustment or disclosure." },
    { id: "ga_gapsme_13", question: "Written Representations --- Intangibles - Obtain management representation confirming completeness, valuation judgments, and ownership." },
    { id: "ga_gapsme_14", question: "Conclusion --- Intangible Assets (GAPSME) - Summarise whether intangible assets are free from material misstatement and properly accounted and disclosed; reference exceptions if any." }
  ],

  "Inventory": [
    { id: "inv_ifrs_1", question: "Risk Assessment & Response Design - Flag IFRS-specific risks: incorrect cost vs NRV under IAS 2, inappropriate overhead absorption, consignment/Incoterms ownership, standard cost variances, WIP measurement.", isRequired: true },
    { id: "inv_ifrs_2", question: "Opening Balances & Lead Schedule - Agree opening balances to prior audited FS; obtain/prepare lead schedule; reconcile to GL and draft IAS 2 disclosures; investigate variances." },
    { id: "inv_ifrs_3", question: "Inventory Count Attendance (ISA 501) - Attend counts where practicable, evaluate client instructions, perform test counts (sheet→floor/floor→sheet) and review count controls; consider alternative procedures if attendance not possible." },
    { id: "inv_ifrs_4", question: "Reconciliation of Count to Final Inventory - Trace original count sheets to final priced inventory; assess adjustments and approvals." },
    { id: "inv_ifrs_5", question: "Ownership, Consignments & Incoterms - Identify goods on consignment, in transit, or at/with third parties; evaluate Incoterms to determine control/ownership; obtain third‑party confirmations." },
    { id: "inv_ifrs_6", question: "Cut‑off (Purchases/Sales) & GRNI - Test the last in/out movements to GRNs/GDNs and invoices; verify GRNI accruals and that revenue cut‑off aligns with transfer of control (IFRS 15 linkage where relevant)." },
    { id: "inv_ifrs_7", question: "Costing & Allocation (IAS 2) - Confirm method (FIFO/Weighted Avg) and that costs include appropriate purchase costs, conversion costs and allocated overheads; test standard cost build‑ups and variance capitalization policies." },
    { id: "inv_ifrs_8", question: "NRV & Provisioning - Test NRV using subsequent sales or market data less selling costs; review slow/obsolete lists and provision methodology; assess reversals of prior write‑downs where applicable." },
    { id: "inv_ifrs_9", question: "Pricing, Extensions & Arithmetic - Agree selected item costs to source documents; reperform line extensions and totals; assess accuracy of unit conversions and BOMs (for WIP/finished goods)." },
    { id: "inv_ifrs_10", question: "Analytics & Reasonableness - Analyze inventory turnover, days on hand, GM% trends by category/location; investigate anomalies and large GRNI/GINI balances." },
    { id: "inv_ifrs_11", question: "Use of Experts (ISA 620) - If a professional valuer/expert is used, evaluate competence and assumptions; corroborate key inputs." },
    { id: "inv_ifrs_12", question: "Presentation & Disclosure (IAS 1/IAS 2) - Check disclosures: accounting policy (cost formula), write‑downs/reversals, carrying amounts by category, pledges/charges; confirm current classification unless cycle exceeds 12 months." },
    { id: "inv_ifrs_13", question: "Subsequent Events - Review post‑year movement in prices/sales and write‑offs; evaluate whether adjustments or disclosures are needed." },
    { id: "inv_ifrs_14", question: "Written Representations - Obtain management reps on ownership, valuation basis (cost/NRV), completeness of counts and disclosures, and any consignment/pledges." },
    { id: "inv_ifrs_15", question: "Conclusion --- Inventory (IFRS) - Conclude on whether inventory is free from material misstatement; record proposed adjustments and control recommendations." },
    { id: "inv_gapsme_1", question: "Risk Assessment & Response Design - Consider inherent risks (e.g., count errors, cut-off around year-end, obsolete/slow-moving stock, cost allocation in manufacturing) and planned responses.", isRequired: true },
    { id: "inv_gapsme_2", question: "Opening Balances & Lead Schedule - Agree opening inventory to prior year accounts. Obtain/prepare the lead schedule and reconcile to GL and draft disclosures. Investigate major variances vs expectations." },
    { id: "inv_gapsme_3", question: "Inventory Count Attendance (ISA 501) - Confirm attendance performed (where feasible). Evaluate client count instructions, observe counts, perform test counts (sheet→floor and floor→sheet), assess controls over tags/sheets and cut-off markings." },
    { id: "inv_gapsme_4", question: "From Count Sheets to Final Inventory - Agree items from original count sheets to final priced inventory sheets; investigate differences and recount adjustments." },
    { id: "inv_gapsme_5", question: "Third‑Party & Consignment Inventory - Identify inventory held BY third parties or AT third-party locations; obtain confirmations; ensure only inventory owned at period end is included; exclude/flag consigned goods appropriately." },
    { id: "inv_gapsme_6", question: "Cut‑off Testing (GRN/GDN) - Test last goods in/out around year-end to GRNs, GDNs, invoices and shipping docs; verify correct period recognition and GRNI/GINI accruals." },
    { id: "inv_gapsme_7", question: "Costing Method & Consistency - Ascertain valuation method (e.g., FIFO/Weighted Avg) and consistency with prior year; confirm acceptability under GAPSME." },
    { id: "inv_gapsme_8", question: "Manufacturing Cost Build‑up - Where applicable, evaluate inclusion of direct labour and overheads; review standard cost build-ups, variance analyses and absorption bases." },
    { id: "inv_gapsme_9", question: "Provisions & NRV - Obtain bases for provisions (obsolete/slow movers, damage, returns). Test NRV via subsequent sales and selling costs. Assess adequacy of write-downs." },
    { id: "inv_gapsme_10", question: "Pricing & Extensions - Test unit costs to supplier invoices/cost sheets; reperform extensions and footings on a sample of inventory lines." },
    { id: "inv_gapsme_11", question: "Professional Valuer / Expert (if applicable) - Consider need for an expert for complex inventories (e.g., livestock, precious metals); evaluate competence and assumptions (ISA 620)." },
    { id: "inv_gapsme_12", question: "Analytics - Perform inventory days, gross margin, and mix analysis; investigate unusual movements (incl. WIP and GRNI)." },
    { id: "inv_gapsme_13", question: "Presentation & Disclosure - Ensure inventory categories and measurement bases disclosed per GAPSME; confirm no inappropriate offsetting; assess current/non-current classification if applicable." },
    { id: "inv_gapsme_14", question: "Subsequent Events & Reversals - Review post-year sales/returns/write-offs; consider reversals of provisions and indicators of post-period adjustments." },
    { id: "inv_gapsme_15", question: "Written Representations - Obtain management reps on ownership, existence, valuation methods/NRV, and completeness of disclosures." },
    { id: "inv_gapsme_16", question: "Conclusion --- Inventory (GAPSME) - Conclude on freedom from material misstatement; summarize exceptions, adjustments and control observations." }
  ],

  "Investment Property": [
    { id: "ip_ifrs_risk_response", question: "Risk Assessment & Response Design - Document risks such as incorrect model selection (cost vs fair value), title issues, custom valuations, and planned responses.", isRequired: true },
    { id: "ip_ifrs_opening_tieback", question: "Opening Balance Tie-back - Agree opening balances with prior FS and note fluctuations." },
    { id: "ip_ifrs_lead_schedule", question: "Schedule Reconciliation - Ensure schedule aligns with GL and note footnotes." },
    { id: "ip_ifrs_analytics", question: "Analytical Review --- Movements & Fair Value Changes - Analyze trends in additions, disposals, and fair value changes, guided by IAS 40 and IFRS 13." },
    { id: "ip_ifrs_additions_disposals", question: "Review Additions & Disposals - Validate additions/disposals via legal docs and board minutes; confirm classification under IAS 40 definition." },
    { id: "ip_ifrs_measurement_model", question: "Measurement After Recognition - Confirm consistent use of cost or fair value model. If cost model used, check depreciation and impairment; if fair value, confirm measurement methods and reliability." },
    { id: "ip_ifrs_impairment_depr", question: "Depreciation (Cost Model) & Impairment Review - Recalculate depreciation, assess impairment indicators and test calculations under IAS 36." },
    { id: "ip_ifrs_inspection_title", question: "Physical Inspection & Title Review - Inspect property and review title deeds/leases for control and existence." },
    { id: "ip_ifrs_cutoff", question: "Cut-off Testing - Ensure additions and disposals around year-end are recorded in the correct accounting period." },
    { id: "ip_ifrs_fairvalue_review", question: "Fair Value Review (Fair Value Model) - If fair value model used, review valuation reports and ensure adherence to IFRS 13 hierarchy and disclosures." },
    { id: "ip_ifrs_disclosures", question: "Disclosure Review --- IAS 40 - Check required notes: model used, reconciliation of balances, valuation methods, lessor disclosures, restrictions, contractual obligations, rental income, and expenses." },
    { id: "ip_ifrs_subsequent_events", question: "Subsequent Events - Review post-year changes (e.g., valuation events, disposals) for necessary adjustments or disclosures." },
    { id: "ip_ifrs_written_reps", question: "Written Representations - Obtain management representation on ownership, classification, valuation model, and completeness." },
    { id: "ip_ifrs_conclusion", question: "Conclusion --- Investment Property (IFRS) - Conclude audit outcome for investment property; detail exceptions if any." },
    { id: "ip_gapsme_risk_response", question: "Risk Assessment & Response Design - Document identified risks (e.g., misclassification, valuation model selection, title issues) and responses.", isRequired: true },
    { id: "ip_gapsme_opening_tieback", question: "Opening Balance Tie-back - Agree opening investment property balances to prior audited FS; investigate discrepancies." },
    { id: "ip_gapsme_lead_schedule", question: "Lead Schedule Reconciliation - Ensure investment property schedule aligns with GL and note disclosures." },
    { id: "ip_gapsme_analytics", question: "Analytical Review --- Movements & Valuation - Perform analytical procedures on additions, disposals, depreciation, and valuation changes to detect anomalies." },
    { id: "ip_gapsme_additions_disposals", question: "Review Additions & Disposals - Inspect contracts, deeds, and board minutes to substantiate additions and disposals classified as investment property per GAPSME §8." },
    { id: "ip_gapsme_measurement", question: "Measurement --- Cost vs Fair Value (Section 8) - Verify consistent application of cost model or fair value model, as permitted by GAPSME." },
    { id: "ip_gapsme_depr_impair", question: "Depreciation & Impairment Review - Recalculate depreciation (if cost model), assess impairment per GAPSME §8 & §12, and verify adjustments." },
    { id: "ip_gapsme_inspection_title", question: "Physical Inspection & Title Verification - Inspect property or verify title deeds/leases to confirm existence and control." },
    { id: "ip_gapsme_cutoff", question: "Cut-off Testing - Verify that year-end additions and disposals are recorded in the correct accounting period." },
    { id: "ip_gapsme_fairvalue_assessment", question: "Fair Value Assessment (if applicable) - For fair value model, examine valuation reports and consider market indicators; ensure consistency with active market inputs." },
    { id: "ip_gapsme_disclosures", question: "Disclosure Review --- GAPSME §8 - Check disclosures on measurement basis, reconciliation of amounts, gain/loss on disposal, and classification for SME size." },
    { id: "ip_gapsme_subsequent_events", question: "Subsequent Events --- Investment Property - Review events such as post-year disposals or reclassifications for recognition or disclosure." },
    { id: "ip_gapsme_written_reps", question: "Written Representations - Obtain management representation regarding completeness, ownership, measurement model, and classification." },
    { id: "ip_gapsme_conclusion", question: "Conclusion --- Investment Property (GAPSME) - State audit conclusion noting whether investment properties are free from material misstatement; reference exceptions." }
  ],

  "Investments": [
    { id: "oi_ifrs_1", question: "Risk Assessment & Response - Identify risks like improper classification between amortised cost / FVTPL / FVOCI.", isRequired: true },
    { id: "oi_ifrs_2", question: "Opening Balance Tie-back - Agree opening balances; assess classification consistency with IFRS 9." },
    { id: "oi_ifrs_3", question: "Schedule Reconciliation - Ensure schedules match GL and note disclosures." },
    { id: "oi_ifrs_4", question: "Analytical Review - Scale trends and movements in investments and compare with market data." },
    { id: "oi_ifrs_5", question: "Additions & Disposals Testing - Validate transactions and verify correct IFRS 9 classification." },
    { id: "oi_ifrs_6", question: "Valuation & Impairment Review - Test fair value (FVTPL/FVOCI) using market data; if amortised cost, test expected credit losses." },
    { id: "oi_ifrs_7", question: "Ownership Verification - Confirm ownership via statements, custodians, etc." },
    { id: "oi_ifrs_8", question: "Cut-off Testing - Test end-of-period trade settlements and recognition timing." },
    { id: "oi_ifrs_9", question: "Unusual Transactions Screening - Investigate anomalies or uncommon transactions for authenticity." },
    { id: "oi_ifrs_10", question: "Disclosure Review -- IFRS 7/9 - Ensure disclosures on classification, fair values, impairments, risk exposure are complete." },
    { id: "oi_ifrs_11", question: "Subsequent Events Review - Review events affecting investments post year-E-end." },
    { id: "oi_ifrs_12", question: "Written Representations - Obtain representation on completeness, classification, valuation basis, and ownership." },
    { id: "oi_ifrs_13", question: "Conclusion --- Other Investments (IFRS) - Provide audit conclusion; mention exceptions or misstatements." },
    { id: "oi_gapsme_1", question: "Risk Assessment & Response - Identify risks (e.g., misclassification, valuation errors) and planned responses.", isRequired: true },
    { id: "oi_gapsme_2", question: "Opening Balance Tie-back - Agree opening balances with prior audited FS; investigate discrepancies." },
    { id: "oi_gapsme_3", question: "Lead Schedule Reconciliation - Reconcile investment schedule with GL and disclosures." },
    { id: "oi_gapsme_4", question: "Analytical Review - Perform analytics on additions, disposals, valuation changes to highlight anomalies." },
    { id: "oi_gapsme_5", question: "Additions & Disposals Testing - Inspect supporting docs; ensure classification under GAPSME (fair value, amortized cost)." },
    { id: "oi_gapsme_6", question: "Valuation Review - For listed: verify market prices; for unlisted: assess valuation basis." },
    { id: "oi_gapsme_7", question: "Ownership Confirmation - Inspect title docs or obtain custodian confirmations." },
    { id: "oi_gapsme_8", question: "Cut-off Testing - Verify correct period recognition of year-end transactions." },
    { id: "oi_gapsme_9", question: "Unusual Transactions Screening - Investigate large/unusual items for authenticity." },
    { id: "oi_gapsme_10", question: "Disclosure Review - Ensure classification (current vs non-current) and disclosure meet GAPSME requirements." },
    { id: "oi_gapsme_11", question: "Subsequent Events Review - Review post-year events (e.g., disposals, fair value changes) for needed adjustments or disclosures." },
    { id: "oi_gapsme_12", question: "Written Representations - Obtain management representation regarding completeness, valuation basis, classification, and ownership." },
    { id: "oi_gapsme_13", question: "Conclusion - State whether other investments are free from material misstatement; highlight any exceptions." }
  ],

  "Payables": [
    { id: "pb_ifrs_1", question: "Risk Assessment & Response Design - Highlight risks such as unrecorded liabilities, improper IFRS 9 measurement (amortised cost), offsetting errors (IAS 32), or incomplete IAS 24 disclosures.", isRequired: true },
    { id: "pb_ifrs_2", question: "Opening Balances Tie-back - Agree opening payables to prior year audited FS; verify brought-forward classifications (current vs non-current)." },
    { id: "pb_ifrs_3", question: "Lead Schedule Reconciliation - Reconcile detailed vendor and other payables listings to the GL and draft note disclosures." },
    { id: "pb_ifrs_4", question: "Analytical Review - Analyze creditor days, purchases vs payables, GRNI, and accruals movements; investigate anomalies." },
    { id: "pb_ifrs_5", question: "Supplier Statements / Confirmations - Perform supplier reconciliations or confirmations on a risk-based sample, addressing un-reconciled items." },
    { id: "pb_ifrs_6", question: "Other Payables Corroboration - Agree tax, payroll, deposits, deferred income, and sundry payables to external filings, contracts, or legal correspondence." },
    { id: "pb_ifrs_7", question: "Subsequent Payments & Unrecorded Liabilities - Scan post-year bank statements and AP ledgers; trace significant payments to year-end liabilities." },
    { id: "pb_ifrs_8", question: "Large/Unusual Balances & Journals - Investigate unusual vendor balances, manual journals, and period-end adjustments; agree to contracts/GRNs." },
    { id: "pb_ifrs_9", question: "Cut-off --- Purchases & Receipt of Goods - Test purchase cut-off to GRNs/inbound logistics and supplier invoices; verify accruals/GRNI recognition." },
    { id: "pb_ifrs_10", question: "Measurement & Interest - Confirm IFRS 9 amortised cost measurement where relevant; assess need to accrue interest/late fees or supplier-financing costs." },
    { id: "pb_ifrs_11", question: "Classification & Offsetting - Evaluate current vs non-current presentation (IAS 1) and the appropriateness of any offsetting (IAS 32)." },
    { id: "pb_ifrs_12", question: "Disclosures --- Related Parties & Terms - Ensure IAS 24 related party balances/terms disclosed; consider liquidity risk maturity analyses where applicable." },
    { id: "pb_ifrs_13", question: "Written Representations - Obtain management reps covering completeness of liabilities, terms, related parties, classification and measurement." },
    { id: "pb_ifrs_14", question: "Conclusion --- Payables & Other Payables (IFRS) - Conclude on freedom from material misstatement; document exceptions and adjustments." },
    { id: "pb_gapsme_1", question: "Risk Assessment & Response Design - Document risks (e.g., unrecorded liabilities, misclassification, duplicate vendors, undisclosed related parties) and planned responses.", isRequired: true },
    { id: "pb_gapsme_2", question: "Opening Balances Tie-back - Agree opening trade and other payables to prior year FS; investigate variances." },
    { id: "pb_gapsme_3", question: "Lead Schedule Reconciliation - Prepare/review the payables lead schedule and reconcile to the GL and draft disclosures." },
    { id: "pb_gapsme_4", question: "Analytical Review - Perform ratio/trend analysis (creditor days, purchases vs payables, GRNI movements); investigate unexpected movements." },
    { id: "pb_gapsme_5", question: "Accruals Listing - Obtain/review accruals listing; test basis, calculations and reversals post year-end." },
    { id: "pb_gapsme_6", question: "Related Parties - Identify/payables to related parties; agree to underlying agreements and ensure disclosure." },
    { id: "pb_gapsme_7", question: "Supplier Statement Reconciliations - Reconcile selected vendor balances to supplier statements or third-party confirmations; resolve reconciling items." },
    { id: "pb_gapsme_8", question: "Other Payables Support - Agree taxes, payroll, deposits, and sundry payables to external correspondence, returns or contracts." },
    { id: "pb_gapsme_9", question: "Subsequent Payments Review - Inspect significant post-year payments to identify unrecorded liabilities at the reporting date." },
    { id: "pb_gapsme_10", question: "Large/Unusual Items - Review and corroborate large/unusual balances and journal entries with underlying documentation." },
    { id: "pb_gapsme_11", question: "Cut-off --- Purchases & GRN - Test purchases around year-end to GRNs, supplier invoices and inventory movements; verify accruals/GRNI." },
    { id: "pb_gapsme_12", question: "Classification & Disclosure - Check current vs non-current split; evaluate offsetting, security/guarantees, covenant terms and related party disclosures per GAPSME." },
    { id: "pb_gapsme_13", question: "Interest & Finance Charges - Assess need to accrue interest/late fees and supplier financing impacts; verify calculations." },
    { id: "pb_gapsme_14", question: "Written Representations - Obtain management reps on completeness of liabilities, terms, related parties and classification." },
    { id: "pb_gapsme_15", question: "Conclusion --- Payables & Other Payables (GAPSME) - Conclude whether balances are free from material misstatement; summarize exceptions and required adjustments." }
  ],

  "PPE": [
    { id: "ppe_ifrs_risk_response", question: "Risk Assessment & Response Design - Document PPE risks, related assertions, and audit responses.", isRequired: true },
    { id: "ppe_ifrs_opening_tieback", question: "Opening Balances Tie-back - Agree opening PPE balances to prior FS/FAS; investigate discrepancies." },
    { id: "ppe_ifrs_lead_schedule", question: "Lead Schedule Prepared & Reconciled - Ensure PPE schedule reconciles to GL and to disclosures." },
    { id: "ppe_ifrs_analytics", question: "Analytical Review -- PPE Movements - Use substantive analytical procedures to identify unexpected fluctuations in PPE additions, disposals, depreciation. Reference ISA 520 methodology." },
    { id: "ppe_ifrs_additions", question: "Review Additions --- Capitalisation Criteria - Inspect invoices and capitalisation thresholds; ensure additions meet IAS 16 recognition criteria (probable economic benefits, reliable cost measurement)." },
    { id: "ppe_ifrs_disposals", question: "Review Disposals & Derecognition - Ensure disposals derecognised correctly; verify gain/loss recorded and assets removed from registers." },
    { id: "ppe_ifrs_depreciation", question: "Depreciation Calculations Reviewed - Recalculate depreciation; check useful lives and methods comply with policy and IAS 16; component approach where material." },
    { id: "ppe_ifrs_impairment", question: "Impairment Review (IAS 36) - Assess indicators of impairment; if present, test impairment calculations and disclosures." },
    { id: "ppe_ifrs_physical_exist", question: "Physical Inspection of PPE - Perform physical count of significant assets to confirm existence and usage." },
    { id: "ppe_ifrs_cutoff", question: "Cut-off Tests -- Period End - Check transactions just before and after period-end to ensure proper recording (completeness and accuracy)." },
    { id: "ppe_ifrs_component", question: "Componentisation (IAS 16) - For items with significant components, verify separate recognition and depreciation per IAS 16." },
    { id: "ppe_ifrs_disclosures", question: "Note Disclosures Review - Review PPE note for required disclosures: basis, depreciation, movements, revaluations, impairment. Reconcile to schedule." },
    { id: "ppe_ifrs_subsequent_events", question: "Subsequent Events --- PPE - Assess post-year-end events, e.g., acquisitions/disposals, for adjustment or disclosure." },
    { id: "ppe_ifrs_written_reps", question: "Written Representations -- PPE - Obtain management representation on completeness, valuation judgments and ownership of PPE." },
    { id: "ppe_ifrs_conclusion", question: "Conclusion --- PPE (IFRS) - State conclusion on whether PPE is free of material misstatement. Reference any exceptions." },
    { id: "ppe_gapsme_risk_response", question: "Risk Assessment & Response Design - Document PPE-related risks aligned with GAPSME Sections 7 & 12, including impairment and depreciation judgment.", isRequired: true },
    { id: "ppe_gapsme_opening_tieback", question: "Opening Balances Tie-back - Agree opening PPE balances to prior FS/SOCIE; investigate any variances." },
    { id: "ppe_gapsme_lead_schedule", question: "Lead Schedule Reconciliation - Ensure PPE schedule matches GL and disclosures." },
    { id: "ppe_gapsme_analytics", question: "Analytical Review -- PPE Movements - Use analytics to identify significant movements; investigate anomalies per ISA 520." },
    { id: "ppe_gapsme_additions", question: "Review Additions --- Capitalisation Criteria - Ensure additions meet recognition criteria under GAPSME Section 7." },
    { id: "ppe_gapsme_disposals", question: "Review Disposals & Derecognition - Verify disposals derecognised appropriately and documentation is complete." },
    { id: "ppe_gapsme_depreciation", question: "Depreciation Calculations Reviewed - Recalculate depreciation; verify consistency with policy and estimation techniques (Section 7)." },
    { id: "ppe_gapsme_impairment", question: "Impairment Review (Section 12) - Evaluate impairment testing performed by management; validate methodology and adjustments." },
    { id: "ppe_gapsme_physical_exist", question: "Physical Inspection of PPE - Physically inspect major fixed assets to confirm existence." },
    { id: "ppe_gapsme_cutoff", question: "Cut-off Tests -- Period End - Verify that PPE transactions are recorded in correct accounting period." },
    { id: "ppe_gapsme_disclosures", question: "Disclosure Review -- Section 7 & SOCIE - Check compliance with GAPSME disclosure requirements: cost model or revaluation movements, impairment, depreciation." },
    { id: "ppe_gapsme_subsequent_events", question: "Subsequent Events --- PPE - Review post-year equity changes (acquisitions/disposals) for appropriate adjustment or disclosure." },
    { id: "ppe_gapsme_written_reps", question: "Written Representations --- PPE - Obtain representation on completeness, valuation judgments, and ownership." },
    { id: "ppe_gapsme_conclusion", question: "Conclusion --- PPE (GAPSME) - Conclude whether PPE is materially accurate and compliant; reference exceptions if any." }
  ],

  "Profit and Loss": [
    { id: "pl_ifrs_1", question: "Risk Assessment & Response Design - IFRS-specific risks: IFRS 15 timing of revenue (transfer of control), variable consideration/returns, principal vs agent, capex vs opex boundary (IAS 38), payroll accruals/benefits (IAS 19), FX (IAS 21), related parties, VAT.", isRequired: true },
    { id: "pl_ifrs_2", question: "Opening Balances & Lead Schedule - Agree opening balances; prepare lead schedules by stream/cost category; reconcile to GL; investigate significant variances vs prior/budget." },
    { id: "pl_ifrs_3", question: "Analytical Review - Perform ratio/trend analytics (GM%, revenue per customer, payroll %, SG&A %). Identify outliers for substantive testing." },
    { id: "pl_ifrs_4a", question: "Revenue Vouching & IFRS 15 Mapping - For samples, trace from contract/order to invoice and receipt; assess performance obligations, timing (point-in-time vs over-time), variable consideration and rights of return; verify credit notes link to specific invoices and correct period." },
    { id: "pl_ifrs_4b", question: "Revenue Cut-off - Test items around year end to shipping/acceptance docs; confirm transfer-of-control criteria; assess principal vs agent if relevant." },
    { id: "pl_ifrs_4c", question: "VAT on Sales - Perform VAT turnover reconciliation; consider indirect tax risk and disclosures if material." },
    { id: "pl_ifrs_5a", question: "CoS/Direct Costs Vouching - Sample invoices/payments; verify supplier, approval, GRN linkage, VAT treatment, and correct allocation to CoS (vs capitalisation under IAS 2/IAS 38 where applicable)." },
    { id: "pl_ifrs_5b", question: "CoS Cut-off - Test purchases and credit notes around year end to GRNs; if Payables cut-off already done, cross-reference and restrict to credit notes as appropriate." },
    { id: "pl_ifrs_5c", question: "VAT on Purchases - Perform inputs reconciliation and assess risk in indirect tax processes." },
    { id: "pl_ifrs_6a", question: "Expenditure Vouching & Capex Boundary - Sample expenses; verify invoice name, approval, VAT, allocation and nature; ensure revenue vs capital classification aligns with IAS 38/IAS 16 policies." },
    { id: "pl_ifrs_6b", question: "Expenditure Cut-off - Review purchase invoices/credit notes either side of year end to confirm correct period recognition." },
    { id: "pl_ifrs_7a", question: "Payroll Analytics & Sampling - Analytics over payroll vs headcount/rates; sample employees to contracts and payroll records; recalc payroll incl. statutory deductions and benefits." },
    { id: "pl_ifrs_7b", question: "Accruals & Provisions - Test holiday pay accruals and other short-term employee benefits; reconcile payroll and deductions control accounts to GL." },
    { id: "pl_ifrs_7c", question: "Existence & Hours/Attendance - For sampled periods, agree hours to timesheets/records; for salaried staff, corroborate existence to HR records; review cash book for unusual payroll items." },
    { id: "pl_ifrs_7d", question: "Directors' Emoluments & Disclosures - Ensure completeness and correct disclosure of directors' remuneration as required by law/IAS 24." },
    { id: "pl_ifrs_8a", question: "Related Parties (IAS 24) - Update related parties; review sales/purchases and transaction histories; scan minutes/records; discuss completeness with management; consider confirmations." },
    { id: "pl_ifrs_8b", question: "Presentation & Disclosure - Review revenue recognition policy and notes (IFRS 15), expense classification (IAS 1), VAT disclosures, FX impacts (IAS 21)." },
    { id: "pl_ifrs_9", question: "Written Representations - Obtain management reps on completeness/accuracy of revenue, expenses, payroll, VAT, related parties and disclosures." },
    { id: "pl_ifrs_10", question: "Conclusion --- Profit & Loss (IFRS) - Conclude whether P&L is free from material misstatement; document exceptions and proposed adjustments." },
    { id: "pl_gapsme_1", question: "Risk Assessment & Response Design - Document P&L risks (unrecorded revenue, cut-off errors, duplicate/fictional expenses, misclassified capex vs opex, payroll accruals, related parties, VAT mistakes, FX). Plan responses.", isRequired: true },
    { id: "pl_gapsme_2", question: "Opening Balances & Lead Schedule - Agree opening balances to prior year FS. Obtain/prepare lead schedules for revenue, CoS/direct costs, admin/selling expenses and wages. Reconcile to GL and investigate major variances." },
    { id: "pl_gapsme_3", question: "Analytical Review - Perform trend/ratio analytics: revenue mix, gross margin %, creditor/debtor days links, payroll % of revenue, variance analysis vs budget/prior. Flag anomalies for testing." },
    { id: "pl_gapsme_4", question: "Large/Unusual Items - Scrutinise P&L for large or unusual entries and vouch to contracts, GRNs/GDNs, delivery notes, approvals and board minutes." },
    { id: "pl_gapsme_5a", question: "Sources & Recording of Income - Ascertain all sources of income and the recording method. Map key flows from source docs to invoice to cash receipt." },
    { id: "pl_gapsme_5b", question: "Revenue Vouching - Sample source documents; trace to invoices and cash receipts; agree calculations; verify approvals; check credit notes link back to specific invoices and correct period." },
    { id: "pl_gapsme_5c", question: "Revenue Cut-off - Test sales invoices and credit notes either side of year end to GDNs/dispatch notes and returns to ensure correct period recognition." },
    { id: "pl_gapsme_5d", question: "VAT on Sales - Perform turnover reconciliation for VAT on sales; evaluate risk of indirect tax errors and review any assessments/disputes." },
    { id: "pl_gapsme_6a", question: "CoS/Direct Costs Vouching - Sample payments/invoices and vouch: correct entity name, approval, link to GRN/delivery note, correct VAT treatment, reasonable allocation to CoS, revenue vs capital nature." },
    { id: "pl_gapsme_6b", question: "CoS Cut-off - Review purchase invoices/credit notes either side of year end with reference to goods received. If already tested in Payables, cross-reference." },
    { id: "pl_gapsme_6c", question: "VAT on Purchases - Perform inputs reconciliation for VAT on purchases; consider risk within indirect tax administration." },
    { id: "pl_gapsme_7a", question: "Expenditure Vouching - Sample expenses; verify invoice name, approval, VAT recovery, allocation, and that the item is revenue (not capital). Analyse material expenses if more assurance is needed." },
    { id: "pl_gapsme_7b", question: "Expenditure Cut-off - Test purchase invoices/credit notes around year end to ensure correct period recognition (may restrict to credit notes if Payables cut-off already completed)." },
    { id: "pl_gapsme_8a", question: "Payroll Analytics & Reasonableness - Analytical review of wages vs headcount and rates; investigate unusual amounts." },
    { id: "pl_gapsme_8b", question: "Payroll Compliance & Recalculation - Agree totals to FS7 (annual) and FS5 (monthly); sample employees to contracts and FS3; recalc payroll incl. NI and Maternity Benefit." },
    { id: "pl_gapsme_8c", question: "Payroll Accruals & Deductions - Prepare payroll and deductions control accounts; test year-end balances. Where material, test holiday pay accruals for a sample of employees; complete payroll tax checklist if needed." },
    { id: "pl_gapsme_8d", question: "Existence & Hours/Attendance - For a sample and periods, agree hours to timesheets (if applicable); where salaried, agree to HR/personnel records; review cash book for unusual payroll items." },
    { id: "pl_gapsme_8e", question: "Directors' Emoluments & Disclosures (if required) - Ensure complete information for directors' emoluments; verify correct disclosure and amounts." },
    { id: "pl_gapsme_9a", question: "Related Parties - Update related parties in permanent file; review sales/purchases lists and transaction histories; scan other records/minutes; discuss completeness with management; consider obtaining confirmations." },
    { id: "pl_gapsme_9b", question: "Presentation & Disclosure - Review quality and consistency of revenue recognition and expense disclosures per GAPSME Sec. 6; assess FX and VAT disclosures (GAPSME Sec. 18)." },
    { id: "pl_gapsme_10", question: "Written Representations - Obtain management reps on completeness and accuracy of revenue, expenses, VAT, payroll, related parties and disclosures." },
    { id: "pl_gapsme_11", question: "Conclusion --- Profit & Loss (GAPSME) - Conclude whether P&L is free from material misstatement; summarise exceptions and proposed adjustments." }
  ],

  "Receivables": [
    { id: "rr_ifrs_1", question: "Risk Assessment & Response Design - Flag risks such as IFRS 9 classification, ECL, or IFRS 15 revenue cut-off errors.", isRequired: true },
    { id: "rr_ifrs_2", question: "Opening Balances Tie-back & Classification - Agree opening entries and verify correct IFRS 9 measurement categories." },
    { id: "rr_ifrs_3", question: "Lead Schedule Reconciliation - Ensure detailed balances align with GL and disclosures under IFRS." },
    { id: "rr_ifrs_4", question: "Analytical Review - Evaluate trends such as days sales outstanding, prepayment usage, and allowance movement." },
    { id: "rr_ifrs_5", question: "Existence & Rights Validation - Use confirmations, receipts, or original docs to verify entitlement and existence." },
    { id: "rr_ifrs_6", question: "Cut-off & Revenue Recognition Testing - Test receivable cut-off under IFRS 15 and verify prepayment matching to performance obligations." },
    { id: "rr_ifrs_7", question: "ECL & Prepayment Amortisation Review - Evaluate ECL model assumptions; confirm correct amortization or recognition of assets." },
    { id: "rr_ifrs_8", question: "Unusual Transactions Screening - Identify and investigate any abnormal receivable or prepayment entries." },
    { id: "rr_ifrs_9", question: "Disclosure Review --- IFRS 7/15/9 - Verify note adequacy: receivable categories, ECL, revenue timing, prepayment terms, risk disclosures." },
    { id: "rr_ifrs_10", question: "Subsequent Events Review - Check post-year cash receipts or utilization of prepayments for any needed adjustments." },
    { id: "rr_ifrs_11", question: "Management Representations - Obtain confirmation on completeness, rights, classification, ECL policy, and matching principles." },
    { id: "rr_ifrs_12", question: "Conclusion --- Receivables & Related Assets (IFRS) - Conclude whether balances are free from material misstatement; note exceptions." },
    { id: "rr_gapsme_1", question: "Risk Assessment & Response Design - Document inherent risks across all receivable-like items and related audit responses.", isRequired: true },
    { id: "rr_gapsme_2", question: "Opening Balance Tie-back - Tie opening balances (receivables, prepayments, other) to prior FS; investigate changes." },
    { id: "rr_gapsme_3", question: "Lead Schedule Reconciliation - Reconcile schedules with GL and note disclosures." },
    { id: "rr_gapsme_4", question: "Analytical Review - Compare aging trends and ratios across full receivable grouping; investigate anomalies." },
    { id: "rr_gapsme_5", question: "Existence & Rights Verification - Use confirmations, bank receipts, or source docs to verify ownership and authenticity." },
    { id: "rr_gapsme_6", question: "Cut-off Testing - Test year-end cut-off for receivables and related assets with supporting documents." },
    { id: "rr_gapsme_7", question: "Valuation & Allowances - Evaluate allowance for doubtful items; confirm prepayments amortize correctly over benefit periods." },
    { id: "rr_gapsme_8", question: "Classification & Presentational Review - Ensure correct classification (current vs non-current), and note disclosures align with GAPSME." },
    { id: "rr_gapsme_9", question: "Unusual Transactions Screening - Investigate any outliers or unfamiliar balances across receivable-related assets." },
    { id: "rr_gapsme_10", question: "Subsequent Events Review - Check post year-end collections or utilization of prepayments for adjustments." },
    { id: "rr_gapsme_11", question: "Management Representation - Obtain formal representations on completeness, rights, valuation, amortization, and classification across all related assets." },
    { id: "rr_gapsme_12", question: "Conclusion --- Receivables & Related Assets (GAPSME) - Summarize audit conclusion and note material exceptions, if any." }
  ],

  "Taxation": [
    { id: "tax_ifrs_1", question: "Risk Assessment & Response Design - IFRS-specific risks: miscalculated current tax, incorrect deferred tax recognition (IAS 12), inappropriate recognition of deferred tax assets, unrecorded contingencies, missing tax reconciliation disclosures, uncertain tax positions (IFRIC 23).", isRequired: true },
    { id: "tax_ifrs_2", question: "Opening Balances & Lead Schedule - Agree opening tax balances to prior audited FS; prepare/review lead schedules; reconcile to GL and computations; investigate unusual movements." },
    { id: "tax_ifrs_3", question: "Current Tax Charge - Reperform tax computations; agree to TB; review adjustments, exemptions and use of losses; assess uncertain tax positions against IFRIC 23 guidance." },
    { id: "tax_ifrs_4", question: "Deferred Tax (IAS 12) - Recalculate deferred tax assets/liabilities on temporary differences; assess probability of recovery of deferred tax assets; test recognition of tax effects on OCI/equity." },
    { id: "tax_ifrs_5", question: "Reconciliation of Tax Liabilities - Reconcile opening→closing current/deferred tax balances; investigate unusual movements; check to supporting documentation." },
    { id: "tax_ifrs_6", question: "Effective Tax Rate & Reconciliation - Prepare reconciliation of tax charge (current + deferred) to profit before tax; analyze ETR vs statutory rate; investigate permanent differences and material reconciling items." },
    { id: "tax_ifrs_7", question: "Disclosures (IAS 12/IAS 1) - Audit notes: tax reconciliation, deferred tax components, expiry of losses, uncertain tax positions, tax charged to OCI/equity, contingent tax liabilities, related parties." },
    { id: "tax_ifrs_8", question: "Written Representations - Obtain management reps on completeness of tax exposures, accuracy of computations, recognition of deferred tax assets, and adequacy of disclosures." },
    { id: "tax_ifrs_9", question: "Conclusion --- Taxation (IFRS) - Conclude whether tax balances and disclosures are fairly presented under IFRS; document exceptions, adjustments and control observations." },
    { id: "tax_gapsme_1", question: "Risk Assessment & Response Design - Key risks: incorrect current/deferred tax calcs, unrecorded liabilities/assets, errors in temporary differences, inappropriate recognition of deferred tax assets, missing GAPSME Sec. 16 disclosures, unusual reconciling items.", isRequired: true },
    { id: "tax_gapsme_2", question: "Opening Balances & Lead Schedule - Agree opening tax balances to prior FS; obtain/prepare tax lead schedule; reconcile to GL and tax computations; investigate significant variances." },
    { id: "tax_gapsme_3", question: "Current Tax Charge - Reperform/direct tax charge calculation from client's computation; check agreement to trial balance; review tax adjustments and exemptions." },
    { id: "tax_gapsme_4", question: "Deferred Tax - Calculate/review deferred tax assets/liabilities on temporary differences; assess recoverability of deferred tax assets; ensure compliance with GAPSME Sec. 16." },
    { id: "tax_gapsme_5", question: "Reconciliation of Tax Liabilities - Reconcile opening→closing tax liabilities; investigate unusual movements; agree balances to supporting schedules and computations." },
    { id: "tax_gapsme_6", question: "Direct Tax Reconciliation - Prepare reconciliation of direct taxation (including deferred) to profit before tax; investigate permanent differences and unusual reconciling items." },
    { id: "tax_gapsme_7", question: "Disclosures - Check notes for required disclosures under GAPSME Sec. 16: tax policies, reconciliation of tax expense to accounting profit, deferred tax composition, expiry of losses, restrictions." },
    { id: "tax_gapsme_8", question: "Written Representations - Obtain management reps on completeness/accuracy of tax computations, deferred tax recognition, contingencies and disclosures." },
    { id: "tax_gapsme_9", question: "Conclusion --- Taxation (GAPSME) - Conclude whether tax balances and disclosures are free from material misstatement; record exceptions, adjustments and control recommendations." }
  ],

  "Investment in Subsidiaries and Associates": [
    { id: "is_ifrs_1", question: "Risk Assessment & Response Design - Include risks such as misapplication of equity method or errors in impairment testing.", isRequired: true },
    { id: "is_ifrs_2", question: "Opening Balance Tie-back - Agree opening investment balances; investigate significant variances." },
    { id: "is_ifrs_3", question: "Schedule Reconciliation - Reconcile investment carrying amounts to GL, disclosures and proportionate share of investees." },
    { id: "is_ifrs_4", question: "Analytical Review -- Equity Method - Compare share of profit/loss and movement to performance of investee." },
    { id: "is_ifrs_5", question: "Additions / Disposals Testing - Validate acquisitions/disposals of investments and correct application of equity method or transition to other accounting (e.g., consolidation)." },
    { id: "is_ifrs_6", question: "Impairment Testing (IAS 36 + IAS 28) - Assess for indicators of impairment and test recoverable amount per IAS 36." },
    { id: "is_ifrs_7", question: "Existence & Documentation - Confirm investee ownership via share certificates, agreements, or confirmations." },
    { id: "is_ifrs_8", question: "Equity Method Computation - Verify that carrying amount reflects initial cost, plus share of post-acquisition profit/loss, less distributions, as per IAS 28." },
    { id: "is_ifrs_9", question: "Upstream & Downstream Transactions - Review and eliminate unrealised profits on intra-group transactions as required by IAS 28." },
    { id: "is_ifrs_10", question: "Cut-off Testing - Ensure profit share and dividends around year-end captured appropriately." },
    { id: "is_ifrs_11", question: "Disclosure Review --- IAS 28 - Check note disclosures: nature and extent of interests, carrying amounts, share of results, impairment losses, etc." },
    { id: "is_ifrs_12", question: "Subsequent Events - Review post-year events (e.g., change in control or influence) affecting accounting treatment." },
    { id: "is_ifrs_13", question: "Written Representations - Obtain representations on classification, completeness, valuation method, and control." },
    { id: "is_ifrs_14", question: "Conclusion --- Investments (IFRS) - Provide audit conclusion on whether investments are free from material misstatement; reference exceptions." },
    { id: "is_gapsme_1", question: "Risk Assessment & Response Design - Document key risks (e.g., improper valuation, incorrect classification) and audit responses.", isRequired: true },
    { id: "is_gapsme_2", question: "Opening Balance Tie-back - Agree opening balances to prior year accounts and investigate differences." },
    { id: "is_gapsme_3", question: "Lead Schedule Reconciliation - Ensure schedule aligns with GL and disclosures." },
    { id: "is_gapsme_4", question: "Analytical Review - Perform review of movements---additions, disposals, valuation changes." },
    { id: "is_gapsme_5", question: "Additions & Disposals Testing - Examine supporting documents for additions/disposals and ensure classification per GAPSME (cost or equity methods)." },
    { id: "is_gapsme_6", question: "Valuation / Impairment Review - For listed investments, corroborate quoted market prices; for unlisted, evaluate basis of valuations. Test for impairment indicators." },
    { id: "is_gapsme_7", question: "Existence & Rights Verification - Inspect title documents or obtain third-party confirmations for shareholding." },
    { id: "is_gapsme_8", question: "Cut-off Testing - Ensure transactions around year-end are recognized in the correct period." },
    { id: "is_gapsme_9", question: "Unusual Transactions Screening - Review for large or unusual items---confirm they represent bona fide transactions." },
    { id: "is_gapsme_10", question: "Disclosure Review - Ensure proper classification between current/non-current, and that disclosures comply with GAPSME." },
    { id: "is_gapsme_11", question: "Subsequent Events Review - Review post-year‐end events such as disposals affecting presentation or need for adjustment." },
    { id: "is_gapsme_12", question: "Written Representations - Obtain representations on completeness, ownership, valuation basis, and classification." },
    { id: "is_gapsme_13", question: "Conclusion --- Investments (GAPSME) - State whether investments in subsidiaries & associates are free from material misstatement; note exceptions." }
  ],

  // fallback used when a classification doesn't have entries yet
  default: [
    { id: "gen_1", question: "Document the objective and scope of the planned procedures." },
    { id: "gen_2", question: "Identify key assertions and relevant risks for this area." },
    { id: "gen_3", question: "Design tests responsive to identified risks, including sampling where relevant." },
  ],
}

export default procedures